export type TypedFilesModulesConfig = {
  /**
   * @description Import location for types generated by typescript operations
   * plugin.
   */
  typesModule: string;

  /**
   * @default false
   * @description By default, only the filename is used to generate TS module
   * declarations. Setting this to `true` will generate it with a full path
   * based on the CWD.
   */
  relativeToCwd?: boolean;

  /**
   * @default *\/
   * @description By default all module declarations will be prefixed with
   * "*\/". Override this to remove or specify a custom prefix (helpful to set
   * to "" in conjunction with relativeToCwd.)
   */
  prefix?: string;

  /**
   * @default "@graphql-typed-document-node/core"
   * @description Import location for TypedDocumentNode.
   */
  typedDocumentNodeModule?: string;

  /**
   * @default false
   * @description Exclude default exports from modules.
   */
  excludeDefaultExports?: boolean;

  // TODO: match typescript naming options
  // https://github.com/dotansimha/graphql-code-generator/blob/master/packages/plugins/other/visitor-plugin-common/src/base-visitor.ts
  // - namingConvention
  // - typesPrefix
  // - typesSuffix
};
